version: "2"

services:

  centos7:
    build:
      context: centos/7
    image: laincloud/centos:latest
    image: laincloud/centos:7
    image: laincloud/centos:7.4.1708

  centos-lain-20171211:
    build:
      context: centos-lain/20171211
    image: laincloud/centos-lain:20171211

  debian-stretch:
    build:
      context: debian/stretch
    image: laincloud/debian:stretch

  golang-1.8.3:
    build:
      context: golang/1.8.3
    image: laincloud/golang:1.8.3
    depends_on:
      - centos7

  golang-1.9.0:
    build:
      context: golang/1.9.0
    image: laincloud/golang:1.9.0
    depends_on:
      - centos7

  java8:
      build:
        context: java/8
      image: laincloud/java:8
      image: laincloud/java:8-jdk
      image: laincloud/java:8u152
      image: laincloud/java:8u152-jdk
      depends_on:
        - centos7

  python-3.6:
    build:
      context: python/3.6
    image: laincloud/python:3.6
    depends_on:
      - centos7

  maven3:
    build:
      context: maven/3.5.0
    image: laincloud/maven:3
    image: laincloud/maven:3.5
    image: laincloud/maven:3.5.0
    depends_on:
      - java8

  maven-kotlin-3.5.0-1.1.3-2:
    build:
      context: maven-kotlin/3.5.0-1.1.3-2
    image: laincloud/maven-kotlin:3.5.0-1.1.3-2
    depends_on:
      - maven-3.5.0

  tomcat8:
    build:
      context: tomcat/8
    image: laincloud/tomcat:8
    image: laincloud/tomcat:8.5
    image: laincloud/tomcat:8.5.20
    depends_on:
      - java8

  node-8.4.0:
    build:
      context: node/8.4.0
    image: laincloud/node:8.4.0
    depends_on:
      - centos7

  golang-node-1.9.0-8.4.0:
    build:
      context: golang-node/1.9.0-8.4.0
    image: laincloud/golang-node:1.9.0-8.4.0
    depends_on:
      - golang-1.9.0
      - node-8.4.0

  nginx-1.13.5:
    build:
      context: nginx/1.13.5
    image: laincloud/nginx:1.13.5
    depends_on:
      - centos7

  jetty9:
    build:
      context: jetty/9
    image: laincloud/jetty:9
    image: laincloud/jetty:9.4
    image: laincloud/jetty:9.4.7
    depends_on:
      - java8

  xgboost-anaconda2-master-4.0.0:
    build:
      context: xgboost-anaconda2/master-4.0.0
    image: laincloud/xgboost-anaconda2:master-4.0.0
    depends_on:
      - debian-stretch
