version: "2"

services:
  centos:
    build:
      context: centos/7.3.1611
      dockerfile: Dockerfile
    image: laincloud/centos:7.3.1611

  debian-stretch:
    build:
      context: debian/stretch
      dockerfile: Dockerfile
    image: laincloud/debian:stretch

  golang-1.8.3:
    build:
      context: golang/1.8.3
      dockerfile: Dockerfile
    image: laincloud/golang:1.8.3
    depends_on:
      - centos

  golang-1.9.0:
    build:
      context: golang/1.9.0
      dockerfile: Dockerfile
    image: laincloud/golang:1.9.0
    depends_on:
      - centos

  java:
    build:
      context: java/8u131
      dockerfile: Dockerfile
    image: laincloud/java:8u131
    depends_on:
      - centos

  maven:
    build:
      context: maven/3.5.0-jdk8u131
      dockerfile: Dockerfile
    image: laincloud/maven:3.5.0-jdk8u131
    depends_on:
      - java

  maven-kotlin:
    build:
      context: maven-kotlin/3.5.0-jdk8u131-1.1.3-2
      dockerfile: Dockerfile
    image: laincloud/maven-kotlin:3.5.0-jdk8u131-1.1.3-2
    depends_on:
      - maven

  tomcat:
    build:
      context: tomcat/8.5.20-jdk8u131
      dockerfile: Dockerfile
    image: laincloud/tomcat:8.5.20-jdk8u131
    depends_on:
      - java

  node-8.4.0:
    build:
      context: node/8.4.0
      dockerfile: Dockerfile
    image: laincloud/node:8.4.0
    depends_on:
      - centos

  golang-node-1.9.0-8.4.0:
    build:
      context: golang-node/1.9.0-8.4.0
      dockerfile: Dockerfile
    image: laincloud/golang-node:1.9.0-8.4.0
    depends_on:
      - golang-1.9.0
      - node-8.4.0

  nginx-1.13.5:
    build:
      context: nginx/1.13.5
      dockerfile: Dockerfile
    image: laincloud/nginx:1.13.5
    depends_on:
      - centos
